[platformio]
default_envs = muse_luxe

[env:muse_luxe]
platform = espressif32@6.10.0
board = esp-wrover-kit
framework = arduino
board_build.partitions = partitions.csv
board_build.flash_mode = dio
board_upload.flash_size = 4MB
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    links2004/WebSockets@2.7.1
    bblanchon/ArduinoJson@7.4.2
    adafruit/Adafruit NeoPixel@1.15.2
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINOJSON_ENABLE_STD_STRING=1

