[platformio]
default_envs = muse_luxe

[env]
platform = espressif32@6.10.0
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    links2004/WebSockets@2.7.1
    bblanchon/ArduinoJson@7.4.2
    adafruit/Adafruit NeoPixel@1.15.2
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINOJSON_ENABLE_STD_STRING=1

[env:muse_luxe]
board = esp-wrover-kit
board_build.partitions = partitions.csv
board_build.flash_mode = dio
board_upload.flash_size = 4MB
build_flags = ${env.build_flags} -DBOARD_MUSE_LUXE=1

[env:spotpear_ball_v2]
board = esp32-s3-devkitc-1
board_build.partitions = partitions-16mb.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = dio
board_upload.flash_size = 16MB
board_upload.maximum_size = 3145728
lib_deps =
    ${env.lib_deps}
    https://github.com/adafruit/Adafruit_GC9A01A.git#a03514ae042e990bc8d16f51aad7e87dabd989b1
    adafruit/Adafruit GFX Library@1.12.6
    adafruit/Adafruit BusIO@1.17.4
build_flags =
    ${env.build_flags}
    -DBOARD_SPOTPEAR_BALL_V2=1
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:waveshare_s3_audio]
board = esp32-s3-devkitc-1
board_build.partitions = partitions-16mb.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = dio
board_upload.flash_size = 16MB
board_upload.maximum_size = 3145728
build_flags =
    ${env.build_flags}
    -DBOARD_WAVESHARE_S3_AUDIO=1
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

